# -*- encoding : utf-8 -*-

deputies = [
{:name=>"Abreu Artiñano Rocío Adriana", :state=>"Campeche", :district=>"2", :email=>"rocio.abreu@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/278.png" },
{:name=>"Aguayo López Miguel Ángel", :state=>"Colima", :district=>"1", :email=>"miguel.aguayo@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/005.png" },
{:name=>"Alcalá Padilla Leobardo", :state=>"Jalisco", :district=>"8", :email=>"leobardo.alcala@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/130.png" },
{:name=>"Allende Cano Ana Isabel", :state=>"Puebla", :district=>"8", :email=>"ana.allende@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/010.png" },
{:name=>"Alvarado Sánchez Brenda María Izontli", :state=>"México", :district=>"11", :email=>"brenda.alvarado@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/022.png" },
{:name=>"Arellano Guzmán Salvador", :state=>"Jalisco", :district=>"4", :email=>"salvador.arellano@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/123.png" },
{:name=>"Arroyo Ruíz Alma Jeanny", :state=>"Veracruz", :district=>"6", :email=>"alma.arroyo@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/077.png" },
{:name=>"Astiazarán Gutiérrez Antonio Francisco", :state=>"Sonora", :district=>"4", :email=>"antonio.astiazaran@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/151.png" },
{:name=>"Athie Flores Kamel", :state=>"Chihuahua", :district=>"7", :email=>"kamel.athie@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/174.png" },
{:name=>"Badillo Ramírez Darío", :state=>"Hidalgo", :district=>"1", :email=>"dario.badillo@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/011.png" },
{:name=>"Barajas del Toro Salvador", :state=>"Jalisco", :district=>"19", :email=>"salvador.barajas@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/124.png" },
{:name=>"Barba Mariscal Marco Antonio", :state=>"Jalisco", :district=>"13", :email=>"marco.barba@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/129.png" },
{:name=>"Barcenas Nieves Delvim Fabiola", :state=>"Querétaro", :district=>"1", :email=>"delvim.barcenas@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/099.png" },
{:name=>"Barrera Barrera Petra", :state=>"Guanajuato", :district=>"1", :email=>"petra.barrera@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/088.png" },
{:name=>"Barrera Estrada Rodimiro", :state=>"Michoacán", :district=>"1", :email=>"rodimiro.barrera@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/063.png" },
{:name=>"Barrera Fortoul Laura", :state=>"México", :district=>"27", :email=>"laura.barrera@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/297.png" },
{:name=>"Barrueta Barón Noé", :state=>"México", :district=>"36", :email=>"noe.barrueta@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/028.png" },
{:name=>"Bautista Villegas Oscar", :state=>"San Luis Potosí", :district=>"3", :email=>"oscar.bautista@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/095.png" },
{:name=>"Bernal Bolnik Sue Ellen", :state=>"México", :district=>"28", :email=>"sue.bernal@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/034.png" },
{:name=>"Berzunza Novelo Landy Margarita", :state=>"Campeche", :district=>"1", :email=>"landy.berzunza@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/079.png" },
{:name=>"Bonilla Gómez Adolfo", :state=>"Zacatecas", :district=>"1", :email=>"adolfo.bonilla@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/121.png" },
{:name=>"Caballero Garza Benito", :state=>"Nuevo León", :district=>"2", :email=>"benito.caballero@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/087.png" },
{:name=>"Caballero Rosiñol Joaquín", :state=>"Veracruz", :district=>"11", :email=>"joaquin.caballero@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/074.png" },
{:name=>"Cabañas Aparicio María Elia", :state=>"Baja California", :district=>"4", :email=>"elia.cabanas@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/132.png" },
{:name=>"Calzada Arroyo Marco Antonio", :state=>"México", :district=>"8", :email=>"marco.calzada@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/036.png" },
{:name=>"Campos Córdova Lisandro Arístides", :state=>"Puebla", :district=>"16", :email=>"lisandro.campos@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/007.png" },
{:name=>"Carbajal Hernández Juan Manuel", :state=>"México", :district=>"33", :email=>"juan.carbajal@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/032.png" },
{:name=>"Cárdenas del Avellano Enrique", :state=>"Tamaulipas", :district=>"5", :email=>"enrique.cardenas@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/108.png" },
{:name=>"Carreón Cervantes Verónica", :state=>"Veracruz", :district=>"7", :email=>"veronica.carreon@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/075.png" },
{:name=>"Carreño Mijares Angelina", :state=>"México", :district=>"4", :email=>"angelina.carreno@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/012.png" },
{:name=>"Castillo Rodríguez Minerva", :state=>"Chihuahua", :district=>"6", :email=>"minerva.castillo@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/177.png" },
{:name=>"Castillo Valdez Benjamin", :state=>"Baja California", :district=>"1", :email=>"benjamin.castillo@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/135.png" },
{:name=>"Charleston Hernández Fernando", :state=>"Veracruz", :district=>"9", :email=>"fernando.charleston@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/061.png" },
{:name=>"Chávez Dávalos Sergio Armando", :state=>"Jalisco", :district=>"7", :email=>"sergio.chavez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/128.png" },
{:name=>"Córdova Díaz Luis Armando", :state=>"Jalisco", :district=>"16", :email=>"luis.cordova@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/131.png" },
{:name=>"Corrales Corrales Francisca Elena", :state=>"Sinaloa", :district=>"6", :email=>"francisca.corrales@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/112.png" },
{:name=>"Curi Naime Alberto", :state=>"México", :district=>"34", :email=>"alberto.curi@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/040.png" },
{:name=>"De la Cruz Requena Rosalba", :state=>"Tamaulipas", :district=>"6", :email=>"rosalba.delacruz@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/107.png" },
{:name=>"De las Fuentes Hernández Fernando Donato", :state=>"Coahuila", :district=>"4", :email=>"fernando.delasfuentes@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/093.png" },
{:name=>"Del Moral Vela Paulina Alejandra", :state=>"México", :district=>"7", :email=>"alejandra.delmoral@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/020.png" },
{:name=>"Delgadillo González Claudia", :state=>"Jalisco", :district=>"11", :email=>"claudia.delgadillo@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/126.png" },
{:name=>"Díaz Athié Antonio De Jesús", :state=>"Chiapas", :district=>"12", :email=>"antonio.diaz@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/068.png" },
{:name=>"Díaz Palacios Víctor Emanuel", :state=>"Puebla", :district=>"3", :email=>"victor.diaz@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/056.png" },
{:name=>"Diez Francos Juan Manuel", :state=>"Veracruz", :district=>"15", :email=>"juan.diez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/059.png" },
{:name=>"Doger Guerrero José Enrique", :state=>"Puebla", :district=>"6", :email=>"jose.doger@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/009.png" },
{:name=>"Domínguez Zepeda Pedro Ignacio", :state=>"Chihuahua", :district=>"8", :email=>"pedro.dominguez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/179.png" },
{:name=>"Duarte Murillo José Ignacio", :state=>"Chihuahua", :district=>"2", :email=>"ignacio.duarte@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/176.png" },
{:name=>"Elizondo Ramírez Irma", :state=>"Coahuila", :district=>"1", :email=>"irma.elizondo@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/091.png" },
{:name=>"Escajeda Jiménez José Rubén", :state=>"Durango", :district=>"3", :email=>"jose.escajeda@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/140.png" },
{:name=>"Félix Chávez Faustino", :state=>"Sonora", :district=>"6", :email=>"faustino.felix@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/150.png" },
{:name=>"Fernández Clamont Francisco Javier", :state=>"México", :district=>"37", :email=>"francisco.fernandez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/026.png" },
{:name=>"Flemate Ramírez Julio César", :state=>"Zacatecas", :district=>"2", :email=>"julio.flemate@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/122.png" },
{:name=>"Flores Gómez José Luis Cruz", :state=>"México", :district=>"10", :email=>"joseluis.flores@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/030.png" },
{:name=>"Flores Méndez José Luis", :state=>"Coahuila", :district=>"2", :email=>"jluis.flores@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/094.png" },
{:name=>"Fuentes Téllez Adriana", :state=>"Chihuahua", :district=>"1", :email=>"afuentes.tellez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/175.png" },
{:name=>"Garay Cabada Marina", :state=>"Veracruz", :district=>"19", :email=>"marina.garay@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/060.png" },
{:name=>"García García Héctor", :state=>"Nuevo León", :district=>"11", :email=>"hgarcia.garcia@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/097.png" },
{:name=>"García Hernández Josefina", :state=>"Puebla", :district=>"4", :email=>"josefina.garcia@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/004.png" },
{:name=>"García Olmedo María del Rocío", :state=>"Puebla", :district=>"13", :email=>"mariadelrocio.garcia@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/001.png" },
{:name=>"García de la Cadena Romero María del Carmen", :state=>"Puebla", :district=>"15", :email=>"maria.garciadelacadena@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/003.png" },
{:name=>"Garza Moreno María Esther", :state=>"Guanajuato", :district=>"4", :email=>"maria.garza@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/090.png" },
{:name=>"Gauna Ruiz de León Celia Isabel", :state=>"Jalisco", :district=>"12", :email=>"celia.gauna@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/144.png" },
{:name=>"Gómez Carmona Blanca Estela", :state=>"México", :district=>"23", :email=>"blanca.gomez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/041.png" },
{:name=>"Gómez Gómez Luis", :state=>"Chiapas", :district=>"5", :email=>"lgomez.gomez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/071.png" },
{:name=>"Gómez Gómez Pedro", :state=>"Chiapas", :district=>"2", :email=>"pgomez.gomez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/070.png" },
{:name=>"Gómez Michel Gabriel", :state=>"Jalisco", :district=>"18", :email=>"gabriel.gomez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/259.png" },
{:name=>"Gómez Olguín Roy Argel", :state=>"Nayarit", :district=>"2", :email=>"roy.gomez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/149.png" },
{:name=>"González Cruz Cristina", :state=>"México", :district=>"39", :email=>"cristina.gonzalez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/038.png" },
{:name=>"González Farias Eligio Cuitláhuac", :state=>"Michoacán", :district=>"8", :email=>"eligio.gonzalez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/050.png" },
{:name=>"González Gómez Cecilia", :state=>"Jalisco", :district=>"3", :email=>"cecilia.gonzalez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/146.png" },
{:name=>"González Reséndiz Rafael", :state=>"Jalisco", :district=>"5", :email=>"rafael.gonzalez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/143.png" },
{:name=>"González Valdez Marco Antonio", :state=>"Nuevo León", :district=>"9", :email=>"marco.gonzalez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/101.png" },
{:name=>"González Vargas Francisco", :state=>"Hidalgo", :district=>"7", :email=>"francisco.gonzalez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/021.png" },
{:name=>"González Martínez Olivares Irazema", :state=>"México", :district=>"24", :email=>"irazema.gonzalezmartinez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/025.png" },
{:name=>"Grajales Palacios Francisco", :state=>"Chiapas", :district=>"7", :email=>"francisco.grajales@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/072.png" },
{:name=>"Gualito Castañeda Rosalba", :state=>"México", :district=>"22", :email=>"rosalba.gualito@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/048.png" },
{:name=>"Guerra Garza Abel", :state=>"Nuevo León", :district=>"3", :email=>"abel.guerra@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/114.png" },
{:name=>"Guevara González Javier Filiberto", :state=>"Puebla", :district=>"14", :email=>"fili.guevara@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/192.png" },
{:name=>"Gurrión Matias Samuel", :state=>"Oaxaca", :district=>"7", :email=>"samuel.gurrion@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/113.png" },
{:name=>"Gutiérrez De la Garza Héctor Humberto", :state=>"Nuevo León", :district=>"5", :email=>"hector.gutierrez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/105.png" },
{:name=>"Gutiérrez Álvarez Harvey", :state=>"Chiapas", :district=>"4", :email=>"harvey.gutierrez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/049.png" },
{:name=>"Hernández Burgos Gaudencio", :state=>"Veracruz", :district=>"5", :email=>"gaudencio.hernandez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/058.png" },
{:name=>"Hernández González Noé", :state=>"Veracruz", :district=>"14", :email=>"noe.hernandez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/066.png" },
{:name=>"Hernández Iñiguez Adriana", :state=>"Michoacán", :district=>"5", :email=>"adriana.hernandez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/057.png" },
{:name=>"Hernández Morales Mirna Esmeralda", :state=>"Hidalgo", :district=>"6", :email=>"mirna.hernandez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/013.png" },
{:name=>"Hernández Tapia Gerardo Xavier", :state=>"México", :district=>"40", :email=>"xavier.hernandez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/015.png" },
{:name=>"Herrera Delgado Jorge", :state=>"Durango", :district=>"4", :email=>"jherrera.delgado@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/138.png" },
{:name=>"Hirata Chico Gilberto Antonio", :state=>"Baja California", :district=>"3", :email=>"gilberto.hirata@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/116.png" },
{:name=>"Inzunza Montoya Alfonso", :state=>"Sinaloa", :district=>"3", :email=>"alfonso.inzunza@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/086.png" },
{:name=>"Juan Marcos Issa Salomón", :state=>"Coahuila", :district=>"5", :email=>"salomon.marcos@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/092.png" },
{:name=>"King De la Rosa Raymundo", :state=>"Quintana Roo", :district=>"2", :email=>"raymundo.king@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/089.png" },
{:name=>"Liceaga Arteaga Gerardo Francisco", :state=>"México", :district=>"2", :email=>"gerardo.liceaga@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/027.png" },
{:name=>"López Alvarado Jaime Chris", :state=>"Baja California", :district=>"6", :email=>"chrislopez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/125.png" },
{:name=>"López Landero Tomás", :state=>"Veracruz", :district=>"18", :email=>"tomas.lopez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/067.png" },
{:name=>"Magaña Zepeda María Angélica", :state=>"Jalisco", :district=>"17", :email=>"maria.magana@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/127.png" },
{:name=>"Maldonado Hernández Fernando Alfredo", :state=>"México", :district=>"18", :email=>"fernando.maldonado@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/042.png" },
{:name=>"Manzur Quiroga José Sergio", :state=>"México", :district=>"9", :email=>"jose.manzur@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/016.png" },
{:name=>"Márquez Martínez José Luis", :state=>"Puebla", :district=>"2", :email=>"jose.marquez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/191.png" },
{:name=>"Márquez Velasco Silvia", :state=>"México", :district=>"14", :email=>"silvia.marquez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/043.png" },
{:name=>"Martínez Cárdenas Esther Angélica", :state=>"San Luis Potosí", :district=>"2", :email=>"esther.martinez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/118.png" },
{:name=>"Mendoza Curiel Ma Leticia", :state=>"Jalisco", :district=>"9", :email=>"leticia.mendoza@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/141.png" },
{:name=>"Mercado Gallegos Sonia Catalina", :state=>"Durango", :district=>"1", :email=>"sonia.mercado@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/137.png" },
{:name=>"Miranda Munive Emilse", :state=>"Hidalgo", :district=>"4", :email=>"emilse.miranda@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/019.png" },
{:name=>"Montano Guzmán José Alejandro", :state=>"Veracruz", :district=>"8", :email=>"jose.montano@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/064.png" },
{:name=>"Montes Alvarado Abraham", :state=>"Chihuahua", :district=>"5", :email=>"abraham.montes@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/187.png" },
{:name=>"Morales Flores Jesús", :state=>"Puebla", :district=>"7", :email=>"jmorales.flores@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/103.png" },
{:name=>"Moreno Montoya J. Pilar", :state=>"Aguascalientes", :district=>"1", :email=>"pilar.moreno@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/080.png" },
{:name=>"Moreno Árcega José Isidro", :state=>"México", :district=>"13", :email=>"jose.moreno@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/044.png" },
{:name=>"Murguía Lardizabal Luis Alfredo", :state=>"Chihuahua", :district=>"4", :email=>"luis.murguia@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/178.png" },
{:name=>"Muñiz Martínez Dulce María", :state=>"Hidalgo", :district=>"2", :email=>"dulce.muniz@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/014.png" },
{:name=>"Nava Gómez José Everardo", :state=>"San Luis Potosí", :district=>"1", :email=>"jeverardo.nava@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/096.png" },
{:name=>"Navarrete Vital Ma. Concepción", :state=>"Guanajuato", :district=>"11", :email=>"concepcion.navarrete@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/102.png" },
{:name=>"Navarro De Alba César Reynaldo", :state=>"México", :district=>"12", :email=>"cesar.navarro@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/031.png" },
{:name=>"Niaves López Ossiel Omar", :state=>"Jalisco", :district=>"15", :email=>"ossiel.niaves@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/134.png" },
{:name=>"Núñez Sánchez Gloria Elizabeth", :state=>"Nayarit", :district=>"3", :email=>"gloria.nunez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/148.png" },
{:name=>"Ochoa Gallegos Williams Oswaldo", :state=>"Chiapas", :district=>"6", :email=>"williams.ochoa@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/078.png" },
{:name=>"Olvera Correa Luis", :state=>"Michoacán", :district=>"6", :email=>"luis.olvera@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/052.png" },
{:name=>"Ordaz Martínez María del Carmen", :state=>"Yucatán", :district=>"2", :email=>"maria.ordaz@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/084.png" },
{:name=>"Ortiz García Salvador", :state=>"Michoacán", :district=>"12", :email=>"salvador.ortiz@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/053.png" },
{:name=>"Padilla Fierro Roman Alfredo", :state=>"Sinaloa", :district=>"1", :email=>"roman.padilla@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/115.png" },
{:name=>"Padilla Navarro Cesario", :state=>"Jalisco", :district=>"1", :email=>"cesario.padilla@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/120.png" },
{:name=>"Pazzi Maza Zita Beatriz", :state=>"Veracruz", :district=>"1", :email=>"zita.pazzi@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/051.png" },
{:name=>"Pérez Anzueto Hugo Mauricio", :state=>"Chiapas", :district=>"11", :email=>"hugo.perez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/069.png" },
{:name=>"Pérez de Alba José Noel", :state=>"Jalisco", :district=>"2", :email=>"jose.perez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/136.png" },
{:name=>"Ponce Orozco Norma", :state=>"México", :district=>"16", :email=>"norma.ponce@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/029.png" },
{:name=>"Quian Alcocer Eduardo Roman", :state=>"Quintana Roo", :district=>"1", :email=>"eduardo.quian@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/083.png" },
{:name=>"Quintana León Socorro de la Luz", :state=>"Michoacán", :district=>"9", :email=>"socorro.quintana@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/045.png" },
{:name=>"Rangel Espinosa José", :state=>"México", :district=>"3", :email=>"jose.rangel@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/018.png" },
{:name=>"Rangel Segovia Alejandro", :state=>"Guanajuato", :district=>"9", :email=>"alejandro.rangel@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/098.png" },
{:name=>"Rellstab Carreto Tanya", :state=>"México", :district=>"35", :email=>"tanya.rellstab@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/024.png" },
{:name=>"Robles Aguirre Mayra Karina", :state=>"Baja California", :district=>"8", :email=>"mayra.robles@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/133.png" },
{:name=>"Rocha Piedra Juan Manuel", :state=>"Nayarit", :district=>"1", :email=>"juan.rocha@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/147.png" },
{:name=>"Rojo García de Alba José Antonio", :state=>"Hidalgo", :district=>"5", :email=>"jose.rojo@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/047.png" },
{:name=>"Román Bojórquez Jesús Tolentino", :state=>"México", :district=>"25", :email=>"jesus.roman@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/023.png" },
{:name=>"Romero Valencia Salvador", :state=>"Michoacán", :district=>"4", :email=>"salvador.romero@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/055.png" },
{:name=>"Rubio Lara Blas Ramón", :state=>"Sinaloa", :district=>"4", :email=>"blas.rubio@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/109.png" },
{:name=>"Ruíz Arriaga Genaro", :state=>"Veracruz", :district=>"3", :email=>"genaro.ruiz@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/062.png" },
{:name=>"Ruíz Moronatti Roberto", :state=>"México", :district=>"6", :email=>"rruiz.moronatti@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/039.png" },
{:name=>"Ruíz Sandoval Cristina", :state=>"México", :district=>"21", :email=>"cristina.ruiz@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/035.png" },
{:name=>"Sahui Rivero Mauricio", :state=>"Yucatán", :district=>"3", :email=>"mauricio.sahui@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/085.png" },
{:name=>"Salgado Peña Abel Octavio", :state=>"Jalisco", :district=>"6", :email=>"abel.salgado@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/142.png" },
{:name=>"Sánchez Cruz Leopoldo", :state=>"Veracruz", :district=>"2", :email=>"leopoldo.sanchez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/073.png" },
{:name=>"Sánchez Romero Carlos", :state=>"Puebla", :district=>"5", :email=>"csanchez.romero@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/006.png" },
{:name=>"Sánchez Santiago María Guadalupe", :state=>"Tlaxcala", :district=>"1", :email=>"mariaguadalupe.sanchez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/037.png" },
{:name=>"Schroeder Verdugo María Fernanda", :state=>"Baja California", :district=>"2", :email=>"maria.schroeder@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/100.png" },
{:name=>"Sosa Altamira William Renan", :state=>"Yucatán", :district=>"1", :email=>"william.sosa@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/081.png" },
{:name=>"Terán Guevara María Rebeca", :state=>"San Luis Potosí", :district=>"7", :email=>"rebeca.teran@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/119.png" },
{:name=>"Terán Juárez Jorge", :state=>"San Luis Potosí", :district=>"4", :email=>"jorge.teran@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/117.png" },
{:name=>"Torres Félix Sergio", :state=>"Sinaloa", :district=>"7", :email=>"sergio.torres@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/111.png" },
{:name=>"Treviño Villarreal Pedro Pablo", :state=>"Nuevo León", :district=>"12", :email=>"pedro.trevino@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/106.png" },
{:name=>"Ugalde Alegría Aurora Denisse", :state=>"México", :district=>"19", :email=>"denisse.ugalde@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/033.png" },
{:name=>"Valdés Palazuelos Jesús Antonio", :state=>"Sinaloa", :district=>"5", :email=>"jesus.valdes@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/110.png" },
{:name=>"Vargas Vargas Laura Guadalupe", :state=>"Puebla", :district=>"1", :email=>"laura.vargas@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/002.png" },
{:name=>"Vázquez Parissi Ponciano", :state=>"Veracruz", :district=>"21", :email=>"ponciano.vazquez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/076.png" },
{:name=>"Vázquez Saut Regina", :state=>"Veracruz", :district=>"20", :email=>"regina.vazquez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/145.png" },
{:name=>"Vela Reyes Marco Alonso", :state=>"Yucatán", :district=>"5", :email=>"marco.vela@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/082.png" },
{:name=>"Velasco Orozco Víctor Hugo", :state=>"Hidalgo", :district=>"3", :email=>"victor.velasco@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/008.png" },
{:name=>"Velázquez Díaz María Guadalupe", :state=>"Guanajuato", :district=>"7", :email=>"maria.velazquez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/104.png" },
{:name=>"Velázquez Ramírez Diana Karina", :state=>"Chihuahua", :district=>"9", :email=>"diana.velazquez@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/189.png" },
{:name=>"Vitela Rodríguez Alma Marina", :state=>"Durango", :district=>"2", :email=>"alma.vitela@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/139.png" },
{:name=>"Zacarías Capuchino Dario", :state=>"México", :district=>"5", :email=>"dario.zacarias@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/054.png" },
{:name=>"Zamora Morales Fernando", :state=>"México", :district=>"26", :email=>"fernando.zamora@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/046.png" },
{:name=>"Zepeda González Francisco Alberto", :state=>"Colima", :district=>"2", :email=>"francisco.zepeda@congreso.gob.mx", :party=>"PRI", :image=>"imgdip/017.png" },
{:name=>"Acosta Croda Rafael", :state=>"Veracruz", :district=>"12", :email=>"rafael.acosta@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/262.png" },
{:name=>"Aguilar Vega Marcos", :state=>"Querétaro", :district=>"3", :email=>"marcos.aguilar@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/237.png" },
{:name=>"Almaguer Torres Felipe de Jesús", :state=>"San Luis Potosí", :district=>"6", :email=>"felipe.almaguer@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/233.png" },
{:name=>"Alonso Morelli Humberto", :state=>"Veracruz", :district=>"4", :email=>"halonso.morelli@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/268.png" },
{:name=>"Angulo Parra Carlos Fernando", :state=>"Chihuahua", :district=>"3", :email=>"carlos.angulo@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/258.png" },
{:name=>"Azuara Zúñiga Xavier", :state=>"San Luis Potosí", :district=>"5", :email=>"xavier.azuara@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/253.png" },
{:name=>"Borboa Becerra Omar Antonio", :state=>"Jalisco", :district=>"10", :email=>"omar.borboa@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/470.png" },
{:name=>"Cárdenas Guízar Gabriel de Jesús", :state=>"Veracruz", :district=>"17", :email=>"gabriel.cardenas@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/269.png" },
{:name=>"Carreño Muro Genaro", :state=>"Guanajuato", :district=>"8", :email=>"genaro.carreno@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/431.png" },
{:name=>"Coronado Quintanilla Alberto", :state=>"Nuevo León", :district=>"6", :email=>"alberto.coronado@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/239.png" },
{:name=>"Dávila Delgado Mario Alberto", :state=>"Coahuila", :district=>"3", :email=>"mario.davila@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/227.png" },
{:name=>"De la Rosa Escalante Arturo", :state=>"Baja California Sur", :district=>"2", :email=>"arturo.delarosa@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/152.png" },
{:name=>"Díaz Trujillo Alberto", :state=>"México", :district=>"15", :email=>"alberto.diaz@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/267.png" },
{:name=>"Fuentes Solís Víctor Oswaldo", :state=>"Nuevo León", :district=>"4", :email=>"victor.fuentes@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/240.png" },
{:name=>"Galindo Delgado David Cuauhtémoc", :state=>"Sonora", :district=>"2", :email=>"david.galindo@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/246.png" },
{:name=>"García González Carlos Alberto", :state=>"Tamaulipas", :district=>"4", :email=>"calberto.garcia@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/153.png" },
{:name=>"García Ramírez José Guadalupe", :state=>"Querétaro", :district=>"4", :email=>"jguadalupe.garcia@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/236.png" },
{:name=>"Gastélum Buenrostro Juan Manuel", :state=>"Baja California", :district=>"5", :email=>"jose.gastelum@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/249.png" },
{:name=>"Gómez Ramírez Raúl", :state=>"Guanajuato", :district=>"10", :email=>"raul.gomez@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/440.png" },
{:name=>"González Serna José Ángel", :state=>"Aguascalientes", :district=>"3", :email=>"jangel.gonzalez@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/229.png" },
{:name=>"Gordillo Castillo Néstor Octavio", :state=>"Puebla", :district=>"12", :email=>"nestor.gordillo@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/264.png" },
{:name=>"Heredia Lizárraga Martín Alonso", :state=>"Sinaloa", :district=>"8", :email=>"martin.heredia@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/248.png" },
{:name=>"Jiménez Castillo Blanca", :state=>"Puebla", :district=>"9", :email=>"bjimenez.castillo@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/265.png" },
{:name=>"Jiménez Esquivel María Teresa", :state=>"Aguascalientes", :district=>"2", :email=>"mteresa.jiemenez@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/232.png" },
{:name=>"Larrazabal Bretón Fernando Alejandro", :state=>"Nuevo León", :district=>"10", :email=>"fernando.larrazabal@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/432.png" },
{:name=>"Llanas Alba José Alejandro", :state=>"Tamaulipas", :district=>"3", :email=>"jose.llanas@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/250.png" },
{:name=>"López Cisneros José Martín", :state=>"Nuevo León", :district=>"7", :email=>"jose.lopez@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/238.png" },
{:name=>"López Landero Leticia", :state=>"Veracruz", :district=>"16", :email=>"llopez.landero@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/270.png" },
{:name=>"López Noriega Alejandra", :state=>"Sonora", :district=>"3", :email=>"alejandra.lopez@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/245.png" },
{:name=>"Lorenzini Rangel Julio Cesar", :state=>"Puebla", :district=>"10", :email=>"julio.lorenzini@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/457.png" },
{:name=>"Niño de Rivera Vela Homero Ricardo", :state=>"Nuevo León", :district=>"1", :email=>"homero.ninoderivera@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/257.png" },
{:name=>"Oliveros Usabiaga José Luis", :state=>"Guanajuato", :district=>"14", :email=>"jose.oliveros@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/495.png" },
{:name=>"Orta Coronado Marcelina", :state=>"Tamaulipas", :district=>"7", :email=>"marcelina.orta@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/242.png" },
{:name=>"Ortiz Mantilla María Isabel", :state=>"Puebla", :district=>"11", :email=>"maria.ortiz@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/261.png" },
{:name=>"Othón Zayas Máximo", :state=>"Sonora", :district=>"7", :email=>"maximo.othon@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/251.png" },
{:name=>"Oviedo Herrera J. Jesús", :state=>"Guanajuato", :district=>"13", :email=>"jesus.oviedo@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/439.png" },
{:name=>"Pacheco Díaz Germán", :state=>"Tamaulipas", :district=>"8", :email=>"german.pacheco@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/243.png" },
{:name=>"Paz Alonzo Raúl", :state=>"Yucatán", :district=>"4", :email=>"raul.paz@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/255.png" },
{:name=>"Pelayo Covarrubias Francisco", :state=>"Baja California Sur", :district=>"1", :email=>"francisco.pelayo@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/065.png" },
{:name=>"Peña Avilés Gerardo", :state=>"Sinaloa", :district=>"2", :email=>"gerardo.pena@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/241.png" },
{:name=>"Prieto Herrera Humberto Armando", :state=>"Tamaulipas", :district=>"2", :email=>"humberto.prieto@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/247.png" },
{:name=>"Quintana Salinas Esther", :state=>"Coahuila", :district=>"7", :email=>"esther.quintana@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/228.png" },
{:name=>"Reina Lizárraga José Enrique", :state=>"Sonora", :district=>"1", :email=>"jose.reina@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/231.png" },
{:name=>"Robledo Leal Ernesto Alfonso", :state=>"Nuevo León", :district=>"8", :email=>"ernesto.robledo@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/230.png" },
{:name=>"Rodríguez Vallejo Diego Sinhué", :state=>"Guanajuato", :district=>"5", :email=>"fernando.rodriguez@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/493.png" },
{:name=>"Salinas Mendiola Glafiro", :state=>"Tamaulipas", :district=>"1", :email=>"glafiro.salinas@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/244.png" },
{:name=>"Serralde Martínez Víctor", :state=>"Veracruz", :district=>"13", :email=>"victor.serralde@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/272.png" },
{:name=>"Sotomayor Chávez Jorge Francisco", :state=>"Distrito Federal", :district=>"15", :email=>"jorge.sotomayor@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/263.png" },
{:name=>"Torres Cofiño Marcelo de Jesús", :state=>"Coahuila", :district=>"6", :email=>"marcelo.torres@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/234.png" },
{:name=>"Vargas Martín del Campo Elizabeth", :state=>"Guanajuato", :district=>"3", :email=>"elizabeth.vargas@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/453.png" },
{:name=>"Villarreal García Ricardo", :state=>"Guanajuato", :district=>"2", :email=>"ricardo.villarreal@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/441.png" },
{:name=>"Zepeda Vidales Damián", :state=>"Sonora", :district=>"5", :email=>"damian.zepeda@congreso.gob.mx", :party=>"PAN", :image=>"imgdip/499.png" },
{:name=>"Águila Torres Claudia Elena", :state=>"Distrito Federal", :district=>"7", :email=>"claudia.aguila@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/203.png" },
{:name=>"Alavez Ruiz Aleida", :state=>"Distrito Federal", :district=>"19", :email=>"aleida.alavez@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/170.png" },
{:name=>"Algredo Jaramillo Edilberto", :state=>"Tlaxcala", :district=>"3", :email=>"edilberto.algredo@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/188.png" },
{:name=>"Amaya Reyes María de Lourdes", :state=>"Distrito Federal", :district=>"25", :email=>"maria.amaya@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/223.png" },
{:name=>"Antonio Altamirano Carol", :state=>"Oaxaca", :district=>"5", :email=>"carol.antonio@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/215.png" },
{:name=>"Aureoles Conejo Silvano", :state=>"Michoacán", :district=>"3", :email=>"silvano.aureoles@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/184.png" },
{:name=>"Barrios Gómez Segués Agustín", :state=>"Distrito Federal", :district=>"10", :email=>"agustin.barriosgomez@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/181.png" },
{:name=>"Bautista Bravo Alliet Mariana", :state=>"México", :district=>"30", :email=>"alliet.bautista@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/198.png" },
{:name=>"Bautista Cuevas Gloria", :state=>"Oaxaca", :district=>"3", :email=>"gloria.bautista@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/206.png" },
{:name=>"Bautista López Victor Manuel", :state=>"México", :district=>"31", :email=>"victor.bautista@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/213.png" },
{:name=>"Blanco Deaquino Silvano", :state=>"Guerrero", :district=>"3", :email=>"silvano.blanco@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/190.png" },
{:name=>"Bojórquez Javier Claudia Elizabeth", :state=>"Tabasco", :district=>"1", :email=>"claudia.bojorquez@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/199.png" },
{:name=>"Brito Lara Tomás", :state=>"Tabasco", :district=>"2", :email=>"tomas.brito@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/160.png" },
{:name=>"Carbajal González Alejandro", :state=>"Distrito Federal", :district=>"8", :email=>"alejandro.carbajal@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/208.png" },
{:name=>"Carpinteyro Calderón Purificación", :state=>"Distrito Federal", :district=>"22", :email=>"purificacion.carpinteyro@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/183.png" },
{:name=>"Carrillo Huerta Mario Miguel", :state=>"Distrito Federal", :district=>"16", :email=>"mario.carrillo@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/171.png" },
{:name=>"Contreras Ceballos Armando", :state=>"Michoacán", :district=>"2", :email=>"armando.contreras@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/219.png" },
{:name=>"Cruz Ramírez Arturo", :state=>"México", :district=>"32", :email=>"arturo.cruz@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/214.png" },
{:name=>"Cuéllar Reyes Fernando", :state=>"Distrito Federal", :district=>"3", :email=>"fernando.cuellar@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/154.png" },
{:name=>"de Jesús Alejandro Carlos", :state=>"Guerrero", :district=>"6", :email=>"carlos.dejesus@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/166.png" },
{:name=>"de la Rosa Peláez Sebastián Alfonso", :state=>"Guerrero", :district=>"8", :email=>"sebastian.delarosa@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/201.png" },
{:name=>"de la Vega Membrillo Jorge Federico", :state=>"México", :district=>"38", :email=>"jorge.delavega@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/211.png" },
{:name=>"Diego Cruz Eva", :state=>"Oaxaca", :district=>"4", :email=>"eva.diego@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/186.png" },
{:name=>"Duarte Ortuño Catalino", :state=>"Guerrero", :district=>"1", :email=>"catalino.duarte@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/196.png" },
{:name=>"Espinosa Cházaro Luis Ángel Xariel", :state=>"Distrito Federal", :district=>"11", :email=>"luis.espinosa@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/155.png" },
{:name=>"Esquivel Zalpa José Luis", :state=>"Michoacán", :district=>"7", :email=>"jose.esquivel@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/168.png" },
{:name=>"Flores Aguayo Uriel", :state=>"Veracruz", :district=>"10", :email=>"uriel.flores@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/205.png" },
{:name=>"Flores Salazar Guadalupe Socorro", :state=>"Distrito Federal", :district=>"27", :email=>"guadalupe.flores@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/173.png" },
{:name=>"García Conejo Antonio", :state=>"Michoacán", :district=>"11", :email=>"agarcia.conejo@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/185.png" },
{:name=>"Gaudiano Rovirosa Gerardo", :state=>"Tabasco", :district=>"4", :email=>"gerardo.gaudiano@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/193.png" },
{:name=>"González Bautista Valentín", :state=>"México", :district=>"29", :email=>"valentin.gonzalez@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/162.png" },
{:name=>"Guzmán Díaz Delfina Elizabeth", :state=>"Oaxaca", :district=>"11", :email=>"delfina.guzman@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/164.png" },
{:name=>"Jardines Fraire Jhonatan", :state=>"Distrito Federal", :district=>"6", :email=>"jhonatan.jardines@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/226.png" },
{:name=>"JarquínHugo", :state=>"Oaxaca", :district=>"8", :email=>"hugo.jarquin@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/163.png" },
{:name=>"Maldonado Salgado José Valentín", :state=>"Distrito Federal", :district=>"23", :email=>"jose.maldonado@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/210.png" },
{:name=>"Martínez Rojas Andrés Eloy", :state=>"Morelos", :district=>"4", :email=>"andres.martinez@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/212.png" },
{:name=>"Medina Filigrana Marcos Rosendo", :state=>"Tabasco", :district=>"5", :email=>"marcos.medina@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/158.png" },
{:name=>"Méndez Denis Lorena", :state=>"Tabasco", :district=>"3", :email=>"lorena.mendez@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/200.png" },
{:name=>"Méndez Martínez Mario Rafael", :state=>"Oaxaca", :district=>"9", :email=>"mario.mendez@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/157.png" },
{:name=>"Merlín García María del Rosario", :state=>"Guerrero", :district=>"9", :email=>"maria.merlin@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/207.png" },
{:name=>"Mícher Camarena Martha Lucía", :state=>"Distrito Federal", :district=>"14", :email=>"malu.micher@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/195.png" },
{:name=>"Miranda Salgado Marino", :state=>"Guerrero", :district=>"2", :email=>"marino.miranda@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/224.png" },
{:name=>"Morales López Carlos Augusto", :state=>"Distrito Federal", :district=>"4", :email=>"caugusto.morales@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/218.png" },
{:name=>"Moreno Rivera Israel", :state=>"Distrito Federal", :district=>"9", :email=>"imoreno.rivera@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/182.png" },
{:name=>"Muñoz Soria José Luis", :state=>"Distrito Federal", :district=>"12", :email=>"jose.munoz@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/180.png" },
{:name=>"Nájera Medina Víctor Reymundo", :state=>"Morelos", :district=>"5", :email=>"victor.najera@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/159.png" },
{:name=>"Navarrete Contreras Joaquina", :state=>"México", :district=>"20", :email=>"joaquina.navarrete@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/209.png" },
{:name=>"Orihuela García Javier", :state=>"Morelos", :district=>"2", :email=>"javier.orihuela@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/156.png" },
{:name=>"Portillo Martínez Vicario", :state=>"Guerrero", :district=>"5", :email=>"vicario.portillo@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/197.png" },
{:name=>"Quiroga Anguiano Karen", :state=>"Distrito Federal", :district=>"18", :email=>"karen.quiroga@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/169.png" },
{:name=>"Reyes Gámiz Roberto Carlos", :state=>"Distrito Federal", :district=>"13", :email=>"roberto.reyes@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/165.png" },
{:name=>"Rodríguez Montero Francisco Tomás", :state=>"Morelos", :district=>"3", :email=>"francisco.rodriguez@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/202.png" },
{:name=>"Rosas Montero Lizbeth Eugenia", :state=>"Distrito Federal", :district=>"1", :email=>"lizbeth.rosas@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/358.png" },
{:name=>"Salazar Trejo Jessica", :state=>"México", :district=>"17", :email=>"jessica.salazar@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/266.png" },
{:name=>"Saldaña Fraire Graciela", :state=>"Quintana Roo", :district=>"3", :email=>"graciela.saldana@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/161.png" },
{:name=>"Salgado Parra Jorge", :state=>"Guerrero", :district=>"7", :email=>"jorge.salgado@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/194.png" },
{:name=>"Sandoval Martínez Hugo", :state=>"Distrito Federal", :district=>"21", :email=>"hugo.sandoval@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/502.png" },
{:name=>"Sansores Sastré Antonio", :state=>"Tabasco", :district=>"6", :email=>"antonio.sansores@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/172.png" },
{:name=>"Villanueva Albarrán Gerardo", :state=>"Distrito Federal", :district=>"24", :email=>"gerardo.villanueva@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/204.png" },
{:name=>"Zárate Salgado Fernando", :state=>"Distrito Federal", :district=>"17", :email=>"fernando.zarate@congreso.gob.mx", :party=>"PRD", :image=>"imgdip/167.png" },
{:name=>"Astudillo Suárez Ricardo", :state=>"Querétaro", :district=>"2", :email=>"rastudillo.suarez@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/271.png" },
{:name=>"Aubry De Castro Palomino Enrique", :state=>"Jalisco", :district=>"14", :email=>"enrique.decastro@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/256.png" },
{:name=>"Camarena García Felipe Arturo", :state=>"Guanajuato", :district=>"12", :email=>"felipe.camarena@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/276.png" },
{:name=>"Guerrero López Judit Magdalena", :state=>"Zacatecas", :district=>"3", :email=>"judit.guerrero@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/280.png" },
{:name=>"López Moreno Lourdes Adriana", :state=>"Chiapas", :district=>"1", :email=>"adriana.lopez@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/282.png" },
{:name=>"Narcia Alvarez Héctor", :state=>"Chiapas", :district=>"10", :email=>"hector.narcia@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/235.png" },
{:name=>"Núñez Aguilar Ernesto", :state=>"Michoacán", :district=>"10", :email=>"ernesto.nunez@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/274.png" },
{:name=>"Pariente Gavito María del Rosario de Fátima", :state=>"Chiapas", :district=>"9", :email=>"maria.pariente@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/275.png" },
{:name=>"Pérez Hernández Rosa Elba", :state=>"Guanajuato", :district=>"6", :email=>"rosaelba.perez@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/277.png" },
{:name=>"Pérez Tejada Padilla David", :state=>"Baja California", :district=>"7", :email=>"david.pereztejada@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/252.png" },
{:name=>"Ramírez Aguilar Oscar Eduardo", :state=>"Chiapas", :district=>"8", :email=>"eduardo.ramirez@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/273.png" },
{:name=>"Romo Fonseca Bárbara Gabriela", :state=>"Zacatecas", :district=>"4", :email=>"barbara.romo@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/279.png" },
{:name=>"Sámano Peralta Miguel", :state=>"México", :district=>"1", :email=>"miguel.samano@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/281.png" },
{:name=>"Villafuerte Trujillo Amílcar Augusto", :state=>"Chiapas", :district=>"3", :email=>"amilcar.villafuerte@congreso.gob.mx", :party=>"Verde", :image=>"imgdip/260.png" },
{:name=>"Coronato Rodríguez José Francisco", :state=>"Morelos", :district=>"1", :email=>"jose.coronato@congreso.gob.mx", :party=>"Movimiento Ciudadano", :image=>"imgdip/390.png" },
{:name=>"Hurtado Gallegos José Antonio", :state=>"Distrito Federal", :district=>"5", :email=>"jose.hurtado@congreso.gob.mx", :party=>"Movimiento Ciudadano", :image=>"imgdip/387.png" },
{:name=>"Jorrín Lozano Victor Manuel", :state=>"Guerrero", :district=>"4", :email=>"victor.jorrin@congreso.gob.mx", :party=>"Movimiento Ciudadano", :image=>"imgdip/449.png" },
{:name=>"Martínez Martínez Juan Luis", :state=>"Oaxaca", :district=>"2", :email=>"juan.martinez@congreso.gob.mx", :party=>"Movimiento Ciudadano", :image=>"imgdip/388.png" },
{:name=>"Soto Martínez José", :state=>"Oaxaca", :district=>"1", :email=>"jsoto.martinez@congreso.gob.mx", :party=>"Movimiento Ciudadano", :image=>"imgdip/389.png" },
{:name=>"Valencia Ramírez Aída Fabiola", :state=>"Oaxaca", :district=>"10", :email=>"aida.valencia@congreso.gob.mx", :party=>"Movimiento Ciudadano", :image=>"imgdip/254.png" },
{:name=>"Benavides Castañeda José Alberto", :state=>"Distrito Federal", :district=>"20", :email=>"jose.benavides@congreso.gob.mx", :party=>"PT", :image=>"imgdip/221.png" },
{:name=>"Huerta Ladrón de Guevara Manuel Rafael", :state=>"Distrito Federal", :district=>"2", :email=>"manuel.huerta@congreso.gob.mx", :party=>"PT", :image=>"imgdip/220.png" },
{:name=>"López Candido José Arturo", :state=>"Distrito Federal", :district=>"26", :email=>"arturo.lopez@congreso.gob.mx", :party=>"PT", :image=>"imgdip/217.png" },
{:name=>"Romero Guzmán Rosa Elia", :state=>"Oaxaca", :district=>"6", :email=>"rosa.romero@congreso.gob.mx", :party=>"PT", :image=>"imgdip/225.png" },
{:name=>"Vega Vázquez José Humberto", :state=>"Tlaxcala", :district=>"2", :email=>"jose.vega@congreso.gob.mx", :party=>"PT", :image=>"imgdip/222.png" }
]


deputies.each do |attributes|
  Deputy.create do |d|
    d.name = attributes[:name]
    d.state = attributes[:state]
    d.district = attributes[:district]
    d.email = attributes[:email]
    d.party = attributes[:party]
    d.image = attributes[:image]
  end
end
puts "termine diputados"
