# -*- encoding : utf-8 -*-

senators = [
{:name=>"Daniel Amador Gaxiola", :state=>"SINALOA", :phone=>"53-45-30-00", :email=>"daniel.amador@senado.gob.mx", :image=>"imgsen/daniel_amador_gaxiola.jpg", :extention=>"3341-3993-3450" },
{:name=>"Joel Ayala Almeida", :state=>"", :phone=>"53-45-30-00", :email=>"jayala@senado.gob.mx", :image=>"imgsen/joel_ayala_almeida.jpg", :extention=>"3257-3694" },
{:name=>"Ricardo Barroso Agramont", :state=>"BAJA CALIFORNIA SUR", :phone=>"53-45-30-00", :email=>"rbarroso@senado.gob.mx", :image=>"imgsen/ricardo_barroso_agramont.jpg", :extention=>"3628-3210" },
{:name=>"Enrique Burgos García", :state=>"QUERETARO", :phone=>"53-45-30-00", :email=>"eburgosg@senado.gob.mx", :image=>"imgsen/enrique_burgos_garcia.jpg", :extention=>"5199-3048" },
{:name=>"Jesús Casillas Romero", :state=>"JALISCO", :phone=>"53-45-30-00", :email=>"jesus.casillas@senado.gob.mx", :image=>"imgsen/jesus_casillas_romero.jpg", :extention=>"3183-3159" },
{:name=>"Manuel Cavazos Lerma", :state=>"TAMAULIPAS", :phone=>"53-45-30-00", :email=>"manuel.cavazos@senado.gob.mx", :image=>"imgsen/manuel_cavazos_lerma.jpg", :extention=>"3359-3978" },
{:name=>"Raúl Cervantes Andrade", :state=>"", :phone=>"53-45-30-00", :email=>"rcervantes@senado.gob.mx", :image=>"imgsen/raul_cervantes_andrade.jpg", :extention=>"3404" },
{:name=>"Miguel Ángel Chico Herrera", :state=>"GUANAJUATO", :phone=>"53-45-30-00", :email=>"mchicoh@senado.gob.mx", :image=>"imgsen/miguel_angel_chico_herrera.jpg", :extention=>"3204" },
{:name=>"Manuel Humberto Cota Jiménez", :state=>"NAYARIT", :phone=>"53-45-30-00", :email=>"cotanayarit@senado.gob.mx", :image=>"imgsen/manuel_cota_humberto_jimenez.jpg", :extention=>"3342-3451" },
{:name=>"Omar Fayad Meneses", :state=>"HIDALGO", :phone=>"53-45-30-00", :email=>"omarfayad@senado.gob.mx", :image=>"imgsen/omar_fayad_meneses.jpg", :extention=>"3072-3997" },
{:name=>"Braulio Manuel Fernández Aguirre", :state=>"COAHUILA", :phone=>"53-45-30-00", :email=>"braulio.fernandez@senado.gob.mx", :image=>"imgsen/braulio_manuel_fernandez_aguirre.jpg", :extention=>"3070-3245" },
{:name=>"Emilio Gamboa Patrón", :state=>"", :phone=>"53-45-30-00", :email=>"emilio.gamboa@senado.gob.mx", :image=>"imgsen/emilio_antonio_gamboa_patron.jpg", :extention=>"3274" },
{:name=>"Ernesto Gándara Camou", :state=>"SONORA", :phone=>"53-45-30-00", :email=>"ernesto.gandara@senado.gob.mx", :image=>"imgsen/ernesto_gandara_camou.jpg", :extention=>"3433-3185" },
{:name=>"Félix Arturo González Canto", :state=>"QUINTANA ROO", :phone=>"53-45-30-00", :email=>"felixagc@senado.gob.mx", :image=>"imgsen/felix_arturo_gonzalez_canto.jpg", :extention=>"3281-5105" },
{:name=>"Isaías González Cuevas", :state=>"BAJA CALIFORNIA SUR", :phone=>"53-45-30-00", :email=>"igonzalez@senado.gob.mx", :image=>"imgsen/isaias_gonzalez_cuevas.jpg", :extention=>"3283-5116" },
{:name=>"Ismael Hernández Deras", :state=>"DURANGO", :phone=>"53-45-30-00", :email=>"ismaelhdezderas@senado.gob.mx", :image=>"imgsen/ismael_alfredo_hernandez_deras.jpg", :extention=>"3228-5122" },
{:name=>"Aarón Irízar López", :state=>"SINALOA", :phone=>"53-45-30-00", :email=>"aaron.irizar@senado.gob.mx", :image=>"imgsen/aaron_irizar_lopez.jpg", :extention=>"3339-3340" },
{:name=>"René Juárez Cisneros", :state=>"GUERRERO", :phone=>"53-45-30-00", :email=>"rene.juarez@senado.gob.mx", :image=>"imgsen/rene_juarez_cisneros.jpg", :extention=>"3346" },
{:name=>"Patricio Martínez García", :state=>"CHIHUAHUA", :phone=>"53-45-30-00", :email=>"patricio@senado.gob.mx", :image=>"imgsen/patricio_martinez_garcia.jpg", :extention=>"3552" },
{:name=>"Humberto Domingo Mayans Canabal", :state=>"TABASCO", :phone=>"53-45-30-00", :email=>"hmayansc@senado.gob.mx", :image=>"imgsen/humberto_domingo_mayans_canabal.jpg", :extention=>"3473 y 5386" },
{:name=>"Armando Neyra Chávez", :state=>"", :phone=>"53-45-30-00", :email=>"aneyra@senado.gob.mx", :image=>"imgsen/armando_neyra_chavez.jpg", :extention=>"3088-3567" },
{:name=>"José Ascención Orihuela Bárcenas", :state=>"MICHOACAN", :phone=>"53-45-30-00", :email=>"jose.orihuela@senado.gob.mx", :image=>"imgsen/jose_ascension_orihuela_barcenas.jpg", :extention=>"3320-3605" },
{:name=>"David Penchyna Grub", :state=>"HIDALGO", :phone=>"53-45-30-00", :email=>"dpenchyna@senado.gob.mx", :image=>"imgsen/david_penchyna_grub.jpg", :extention=>"3166" },
{:name=>"Eviel Pérez Magaña", :state=>"OAXACA", :phone=>"53-45-30-00", :email=>"eviel.perez@senado.gob.mx", :image=>"imgsen/eviel_perez_magana.jpg", :extention=>"3319-3045-5068" },
{:name=>"Raúl Aarón Pozos Lanz", :state=>"CAMPECHE", :phone=>"53-45-30-00", :email=>"rpozos@senado.gob.mx", :image=>"imgsen/raul_aaron_pozos_lanz.jpg", :extention=>"3490-5205" },
{:name=>"Carlos Romero Deschamps", :state=>"", :phone=>"53-45-30-00", :email=>"carlos.romero@senado.gob.mx", :image=>"imgsen/carlos_antonio_romero_dechamps.jpg", :extention=>"5442-3028" },
{:name=>"Miguel Romo Medina", :state=>"AGUASCALIENTES", :phone=>"53-45-30-00", :email=>"miguel.romo@senado.gob.mx", :image=>"imgsen/miguel_romo_medina.jpg", :extention=>"3463-5206" },
{:name=>"Óscar Román Rosas González", :state=>"CAMPECHE", :phone=>"53-45-30-00", :email=>"oscarrosas@senado.gob.mx", :image=>"imgsen/oscar_roman_rosas_gonzalez.jpg", :extention=>"5448-3501" },
{:name=>"Gerardo Sánchez García", :state=>"", :phone=>"53-45-30-00", :email=>"gerardo.sanchez@senado.gob.mx", :image=>"imgsen/gerardo_sanchez_garcia.jpg", :extention=>"3380-3922-3390" },
{:name=>"Alejandro Tello Cristerna", :state=>"ZACATECAS", :phone=>"53-45-30-00", :email=>"alejandro.telloc@senado.gob.mx", :image=>"imgsen/alejandro_tello_cristerna.jpg", :extention=>"5210-3434" },
{:name=>"Teófilo Torres Corzo", :state=>"SAN LUIS POTOSI", :phone=>"53-45-30-00", :email=>"teofilo.torres@senado.gob.mx", :image=>"imgsen/teofilo_torres_corzo.jpg", :extention=>"3097-3080" },
{:name=>"Héctor Yunes Landa", :state=>"VERACRUZ", :phone=>"53-45-30-00", :email=>"hector.yunes@senado.gob.mx", :image=>"imgsen/hector_yunes_landa.jpg", :extention=>"3973-3053" },
{:name=>"José Francisco Yunes Zorrilla", :state=>"VERACRUZ", :phone=>"53-45-30-00", :email=>"jose.yunes@senado.gob.mx", :image=>"imgsen/jose_francisco_yunes_zorrilla.jpg", :extention=>"3078-5249" },
{:name=>"Arturo Zamora Jiménez", :state=>"JALISCO", :phone=>"53-45-30-00", :email=>"azamoraj@senado.gob.mx", :image=>"imgsen/arturo_zamora_jimenez.jpg", :extention=>"5157-3052" },
{:name=>"José Rosas Aispuro Torres", :state=>"DURANGO", :phone=>"53-45-30-00", :email=>"j.aispuro@senado.gob.mx", :image=>"imgsen/jose_rosas_aispuro_torres.jpg", :extention=>"3011" },
{:name=>"Daniel Gabriel Ávila Ruiz", :state=>"YUCATAN", :phone=>"53-45-30-00", :email=>"daniel.avila@senado.gob.mx", :image=>"imgsen/daniel_gabriel_avila_ruiz.jpg", :extention=>"3327" },
{:name=>"Francisco de Paula Búrquez Valenzuela", :state=>"SONORA", :phone=>"53-45-30-00", :email=>"francisco.burquez@senado.gob.mx", :image=>"imgsen/francisco_de_paula_burquez_valenzuela.jpg", :extention=>"" },
{:name=>"Ernesto Javier Cordero Arroyo", :state=>"", :phone=>"53-45-30-00", :email=>"ernesto.cordero@pan.@senado.gob.mx", :image=>"imgsen/ernesto_cordero_arroyo.jpg", :extention=>"2205-2206" },
{:name=>"Javier Corral Jurado", :state=>"CHIHUAHUA", :phone=>"53-45-30-00", :email=>"javier.corral@senado.gob.mx", :image=>"imgsen/javier_corral_jurado.jpg", :extention=>"3035-3432" },
{:name=>"Francisco Domínguez Servién", :state=>"QUERETARO", :phone=>"53-45-30-00", :email=>"panchodominguez@senado.gob.mx", :image=>"imgsen/francisco_dominguez_servien.jpg", :extention=>"3409-5348" },
{:name=>"Francisco García Cabeza de Vaca", :state=>"TAMAULIPAS", :phone=>"53-45-30-00", :email=>"franciscocabezadevaca@senado.gob.mx", :image=>"imgsen/francisco_javier_garcia_cabeza_de_vaca.jpg", :extention=>"3022-5245" },
{:name=>"Roberto Gil Zuarth", :state=>"", :phone=>"53-45-30-00", :email=>"roberto.gil@senado.gob.mx", :image=>"imgsen/roberto_gil_zuarth.jpg", :extention=>"3084-3569" },
{:name=>"Raúl Gracia Guzmán", :state=>"NUEVO LEON", :phone=>"53-45-30-00", :email=>"rgraciag@senado.gob.mx", :image=>"imgsen/raul_gracia_guzman.jpg", :extention=>"3395-3495" },
{:name=>"Víctor Hermosillo y Celada", :state=>"BAJA CALIFORNIA", :phone=>"53-45-30-00", :email=>"victor.hermosillo@senado.gob.mx", :image=>"imgsen/victor_hermosillo_celada.jpg", :extention=>"3580-3026-3027" },
{:name=>"Fernando Herrera Ávila", :state=>"AGUASCALIENTES", :phone=>"53-45-30-00", :email=>"fernandoh@senado.gob.mx", :image=>"imgsen/fernando_herrera_avila.jpg", :extention=>"3096" },
{:name=>"Héctor Larios Córdova", :state=>"", :phone=>"53-45-30-00", :email=>"hlarios@senado.gob.mx", :image=>"imgsen/hector_larios_cordova.jpg", :extention=>"3699-3374" },
{:name=>"Jorge Luis Lavalle Maury", :state=>"CAMPECHE", :phone=>"53-45-30-00", :email=>"jorge.lavalle@senado.gob.mx", :image=>"imgsen/jorge_luis_lavalle_maury.jpg", :extention=>"3216" },
{:name=>"Francisco Salvador López Brito", :state=>"SINALOA", :phone=>"53-45-30-00", :email=>"flopez.brito@pan.@senado.gob.mx", :image=>"imgsen/francisco_salvador_lopez_brito.jpg", :extention=>"3106-5168" },
{:name=>"Javier Lozano Alarcón", :state=>"PUEBLA", :phone=>"53-45-30-00", :email=>"javierlozano@senado.gob.mx", :image=>"imgsen/javier_lozano_alarcon.jpg", :extention=>"3219" },
{:name=>"José María Martínez Martínez", :state=>"JALISCO", :phone=>"53-45-30-00", :email=>"josemariamartinez@senado.gob.mx", :image=>"imgsen/jose_maria_martinez_martinez.jpg", :extention=>"3472" },
{:name=>"Carlos Mendoza Davis", :state=>"BAJA CALIFORNIA SUR", :phone=>"53-45-30-00", :email=>"cmendozadavis@senado.gob.mx", :image=>"imgsen/carlos_mendoza_davis.jpg", :extention=>"3082-3081" },
{:name=>"Martín Orozco Sandoval", :state=>"AGUASCALIENTES", :phone=>"53-45-30-00", :email=>"morozco@senado.gob.mx", :image=>"imgsen/martin_orozco_sandoval.jpg", :extention=>"3328" },
{:name=>"César Octavio Pedroza Gaitán", :state=>"SAN LUIS POTOSI", :phone=>"53-45-30-00", :email=>"octavio.pedroza@senado.gob.mx", :image=>"imgsen/cesar_octavio_pedroza_gaitan.jpg", :extention=>"3042" },
{:name=>"Jorge Luis Preciado Rodríguez", :state=>"COLIMA", :phone=>"53-45-30-00", :email=>"jpreciado@senado.gob.mx", :image=>"imgsen/jorge_luis_preciado_rodriguez.jpg", :extention=>"3029-3030" },
{:name=>"Juan Carlos Romero Hicks", :state=>"GUANAJUATO", :phone=>"53-45-30-00", :email=>"romero.hicks@senado.gob.mx", :image=>"imgsen/juan_carlos_romero_hicks.jpg", :extention=>"3301-5360" },
{:name=>"Ernesto Ruffo Appel", :state=>"BAJA CALIFORNIA", :phone=>"53-45-30-00", :email=>"ernesto.ruffo@senado.gob.mx", :image=>"imgsen/ernesto_ruffo_appel.jpg", :extention=>"5217-5359-3628" },
{:name=>"Luis Fernando Salazar Fernández", :state=>"COAHUILA", :phone=>"53-45-30-00", :email=>"lfsalazar@senado.gob.mx", :image=>"imgsen/luis_fernando_salazar_fernandez.jpg", :extention=>"" },
{:name=>"Fernando Torres Graciano", :state=>"GUANAJUATO", :phone=>"53-45-30-00", :email=>"torresgraciano@senado.gob.mx", :image=>"imgsen/fernando_torres_graciano.jpg", :extention=>"5443-3424" },
{:name=>"Salvador Vega Casillas", :state=>"", :phone=>"53-45-30-00", :email=>"salvador.vega@senado.gob.mx", :image=>"imgsen/salvador_vega_casillas.jpg", :extention=>"3323" },
{:name=>"Fernando Yunes Márquez", :state=>"VERACRUZ", :phone=>"53-45-30-00", :email=>"fernandoyunes@senado.gob.mx", :image=>"imgsen/fernando_yunes_marquez.jpg", :extention=>"3325-5458" },
{:name=>"Luis Miguel Gerónimo Barbosa Huerta", :state=>"", :phone=>"53-45-30-00", :email=>"miguel.barbosa@senado.gob.mx", :image=>"imgsen/luis_miguel_geronimo_barbosa_huerta.jpg", :extention=>"3158-3116" },
{:name=>"Víctor Manuel Camacho Solís", :state=>"", :phone=>"53-45-30-00", :email=>"manuel.camacho@senado.gob.mx", :image=>"imgsen/victor_manuel_camacho_solis.jpg", :extention=>"3196-5223" },
{:name=>"Mario Delgado Carrillo", :state=>"DISTRITO FEDERAL", :phone=>"53-45-30-00", :email=>"mario.delgado@senado.gob.mx", :image=>"imgsen/mario_martin_delgado_carrillo.jpg", :extention=>"3470-3827" },
{:name=>"Fidel Demédicis Hidalgo", :state=>"MORELOS", :phone=>"53-45-30-00", :email=>"fidel.demedicis@senado.gob.mx", :image=>"imgsen/fidel_demedicis_hidalgo.jpg", :extention=>"3561" },
{:name=>"Alejandro de Jesús Encinas Rodríguez", :state=>"MEXICO", :phone=>"53-45-30-00", :email=>"aencinas@senado.gob.mx", :image=>"imgsen/Alejandro_Encinas.jpg", :extention=>"3112-3961" },
{:name=>"Adán Augusto López Hernández", :state=>"TABASCO", :phone=>"53-45-30-00", :email=>"adanaugusto@senado.gob.mx", :image=>"imgsen/adan_augusto_lopez_hernandez.jpg", :extention=>"3134-3308" },
{:name=>"Fernando Enrique Mayans Canabal", :state=>"TABASCO", :phone=>"53-45-30-00", :email=>"fmayans@senado.gob.mx", :image=>"imgsen/fernando_enrique_mayans_canabal.jpg", :extention=>"3194-5290" },
{:name=>"Raúl Morón Orozco", :state=>"MICHOACAN", :phone=>"53-45-30-00", :email=>"rmoron@senado.gob.mx", :image=>"imgsen/raul_moron_orozco.jpg", :extention=>"3203-5143" },
{:name=>"Isidro Pedraza Chávez", :state=>"HIDALGO", :phone=>"53-45-30-00", :email=>"isidro.pedraza@senado.gob.mx", :image=>"imgsen/isidro_pedraza_chavez.jpg", :extention=>"3111-5300" },
{:name=>"Sofío Ramírez Hernández", :state=>"GUERRERO", :phone=>"53-45-30-00", :email=>"sofioramirez@senado.gob.mx", :image=>"imgsen/socorro_sofio_ramirez_fernandez.jpg", :extention=>"3133-5269" },
{:name=>"Armando Ríos Piter", :state=>"GUERRERO", :phone=>"53-45-30-00", :email=>"armando.rios@senado.gob.mx", :image=>"imgsen/armando_rios_piter.jpg", :extention=>"3272" },
{:name=>"Zoé Robledo Aburto", :state=>"CHIAPAS", :phone=>"53-45-30-00", :email=>"zoerobledo@senado.gob.mx", :image=>"imgsen/zoe_alejandro_robledo_aburto.jpg", :extention=>"3273-5198" },
{:name=>"Ángel Benjamín Robles Montoya", :state=>"OAXACA", :phone=>"53-45-30-00", :email=>"benjaminrobles@senado.gob.mx", :image=>"imgsen/angel_benjamin_robles_montoya.jpg", :extention=>"3118-3117-5132" },
{:name=>"Adolfo Romero Lainas", :state=>"OAXACA", :phone=>"53-45-30-00", :email=>"adolfo.romero@senado.gob.mx", :image=>"imgsen/adolfo_romero_lainas.jpg", :extention=>"3251-5228" },
{:name=>"Rabindranath Salazar Solorio", :state=>"MORELOS", :phone=>"53-45-30-00", :email=>"rabindranath.salazar@senado.gob.mx", :image=>"imgsen/rabindranath_salazar_solorio.jpg", :extention=>"3123-3124" },
{:name=>"Luis Sánchez Jiménez", :state=>"", :phone=>"53-45-30-00", :email=>"luis.sanchez@senado.gob.mx", :image=>"imgsen/luis_venancio_sanchez_jimenez.jpg", :extention=>"3834-3965-3407" },
{:name=>"Pablo Escudero Morales", :state=>"DISTRITO FEDERAL", :phone=>"53-45-30-00", :email=>"pablo.escudero@senado.gob.mx", :image=>"imgsen/pablo_escudero_morales.jpg", :extention=>"3293-5170" },
{:name=>"Juan Gerardo Flores Ramírez", :state=>"", :phone=>"53-45-30-00", :email=>"gerardo.flores@senado.gob.mx", :image=>"imgsen/juan_gerardo_flores_ramirez.jpg", :extention=>"" },
{:name=>"Jorge Emilio González Martínez", :state=>"QUINTANA ROO", :phone=>"53-45-30-00", :email=>"egonzalezm@senado.gob.mx", :image=>"imgsen/jorge_emilio_gonzalez_martinez.jpg", :extention=>"3763-3762" },
{:name=>"Luis Armando Melgar Bravo", :state=>"CHIAPAS", :phone=>"53-45-30-00", :email=>"lamelgar@senado.gob.mx", :image=>"imgsen/luis_armando_melgar_bravo.jpg", :extention=>"5434-5435" },
{:name=>"Carlos Alberto Puente Salas", :state=>"ZACATECAS", :phone=>"53-45-30-00", :email=>"carlospuente@senado.gob.mx", :image=>"imgsen/carlos_alberto_puente_salas.jpg", :extention=>"3563-4116-4115" },
{:name=>"Manuel Bartlett Díaz", :state=>"", :phone=>"53-45-30-00", :email=>"mbartlett@senado.gob.mx", :image=>"imgsen/manuel_bartlett_diaz.jpg", :extention=>"5479-5461" },
{:name=>"Marco Antonio Blásquez Salinas", :state=>"BAJA CALIFORNIA", :phone=>"53-45-30-00", :email=>"marcobla@senado.gob.mx", :image=>"imgsen/marco_antonio_blasquez_salinas.jpg", :extention=>"3246-3850-3925" },
{:name=>"David Monreal Ávila", :state=>"ZACATECAS", :phone=>"53-45-30-00", :email=>"david.monreal@senado.gob.mx", :image=>"imgsen/david_monreal_avila.jpg", :extention=>"3054" },
{:name=>"Blanca María del Socorro Alcalá Ruiz", :state=>"PUEBLA", :phone=>"53-45-30-00", :email=>"blanca.alcala@senado.gob.mx", :image=>"imgsen/blanca_maria_del_socorro_alcala_ruiz.jpg", :extention=>"5383-3440" },
{:name=>"Ivonne Liliana Álvarez García", :state=>"NUEVO LEON", :phone=>"53-45-30-00", :email=>"ivonnealvarez@senado.gob.mx", :image=>"imgsen/ivonne_liliana_alvarez_garcia.jpg", :extention=>"2373-2211" },
{:name=>"Angélica del Rosario Araujo Lara", :state=>"YUCATAN", :phone=>"53-45-30-00", :email=>"angelica.araujo@senado.gob.mx", :image=>"imgsen/angelica_del_rosario_araujo_lara.jpg", :extention=>"3036" },
{:name=>"María Cristina Díaz Salazar", :state=>"", :phone=>"53-45-30-00", :email=>"cristina.diazs09@senado.gob.mx", :image=>"imgsen/maria_cristina_diaz_salazar.jpg", :extention=>"3345-3454" },
{:name=>"Hilda Esthela Flores Escalera", :state=>"", :phone=>"53-45-30-00", :email=>"hilda.flores@senado.gob.mx", :image=>"imgsen/hilda_esthela_flores_escalera.jpg", :extention=>"3284-3506" },
{:name=>"Margarita Flores Sánchez", :state=>"NAYARIT", :phone=>"53-45-30-00", :email=>"margarita.flores@senado.gob.mx", :image=>"imgsen/margarita_flores_sanchez.jpg", :extention=>"3333-3423-3317" },
{:name=>"Diva Hadamira Gastélum Bajo", :state=>"", :phone=>"53-45-30-00", :email=>"diva.gastelum@senado.gob.mx", :image=>"imgsen/diva_hadamira_gastelum_bajo.jpg", :extention=>"3309-3410" },
{:name=>"Arely Gómez González", :state=>"", :phone=>"53-45-30-00", :email=>"arelygomezg@senado.gob.mx", :image=>"imgsen/arely_gomez_gonzalez.jpg", :extention=>"3452" },
{:name=>"Marcela Guerra Castillo", :state=>"NUEVO LEON", :phone=>"53-45-30-00", :email=>"marcela.guerra@senado.gob.mx", :image=>"imgsen/marcela_guerra_castillo.jpg", :extention=>"3157" },
{:name=>"Lisbeth Hernández Lecona", :state=>"MORELOS", :phone=>"53-45-30-00", :email=>"lisbeth.hernandez@senado.gob.mx", :image=>"imgsen/lisbet_hernandez_lecona.jpg", :extention=>"3224-5301" },
{:name=>"Juana Leticia Herrera Ale", :state=>"DURANGO", :phone=>"53-45-30-00", :email=>"leticia.herrera@senado.gob.mx", :image=>"imgsen/juana_leticia_herrera_ale.jpg", :extention=>"3184-5303" },
{:name=>"Ana Lilia Herrera Anzaldo", :state=>"MEXICO", :phone=>"53-45-30-00", :email=>"analiliaherrera@senado.gob.mx", :image=>"imgsen/ana_lilia_herrera_anzaldo.jpg", :extention=>"3379-5319" },
{:name=>"Lilia Guadalupe Merodio Reza", :state=>"CHIHUAHUA", :phone=>"53-45-30-00", :email=>"lilia.merodio@senado.gob.mx", :image=>"imgsen/lidia_guadalupe_merodio_reza.jpg", :extention=>"3046-5309" },
{:name=>"Graciela Ortiz González", :state=>"", :phone=>"53-45-30-00", :email=>"graciela.ortiz@senado.gob.mx", :image=>"imgsen/graciela_ortiz_gonzalez.jpg", :extention=>"3497-5203" },
{:name=>"Claudia Artemiza Pavlovich Arellano", :state=>"SONORA", :phone=>"53-45-30-00", :email=>"claudiapavlovich@senado.gob.mx", :image=>"imgsen/claudia_artemiza_pavlovich_arellano.jpg", :extention=>"3003-3576" },
{:name=>"María del Rocío Pineda Gochi", :state=>"MICHOACAN", :phone=>"53-45-30-00", :email=>"rocio.pineda@senado.gob.mx", :image=>"imgsen/maria_del_rocio_pineda_gochi.jpg", :extention=>"3087-5332" },
{:name=>"Itzel Sarahí Ríos de la Mora", :state=>"COLIMA", :phone=>"53-45-30-00", :email=>"itzel.rios@senado.gob.mx", :image=>"imgsen/itzel_sarahi_rios_de_la_mora.jpg", :extention=>"5437-5436" },
{:name=>"Mely Romero Celis", :state=>"COLIMA", :phone=>"53-45-30-00", :email=>"mely.romero@senado.gob.mx", :image=>"imgsen/mely_romero_celis.jpg", :extention=>"5349-3481" },
{:name=>"María Lucero Saldaña Pérez", :state=>"PUEBLA", :phone=>"53-45-30-00", :email=>"lucero.saldana@senado.gob.mx", :image=>"imgsen/maria_lucero_saldana_perez.jpg", :extention=>"3588-3141" },
{:name=>"Luisa María Calderón Hinojosa", :state=>"", :phone=>"53-45-30-00", :email=>"lcalderonh@senado.gob.mx", :image=>"imgsen/luisa_maria_de_guadalupe_calderon_hinojosa.jpg", :extention=>"3234-3005" },
{:name=>"Gabriela Cuevas Barrón", :state=>"", :phone=>"53-45-30-00", :email=>"gabriela.cuevas@senado.gob.mx", :image=>"imgsen/gabriela_cuevas_barron.jpg", :extention=>"3213-3214" },
{:name=>"Adriana Dávila Fernández", :state=>"TLAXCALA", :phone=>"53-45-30-00", :email=>"adavilaf@senado.gob.mx", :image=>"imgsen/adriana_davila_fernandez.jpg", :extention=>"5078-3627" },
{:name=>"Rosa Adriana Díaz Lizama", :state=>"YUCATAN", :phone=>"53-45-30-00", :email=>"rosa.diaz@senado.gob.mx", :image=>"imgsen/rosa_adriana_diaz_lisama.jpg", :extention=>"3068-5451-3065" },
{:name=>"Martha Elena García Gómez", :state=>"NAYARIT", :phone=>"53-45-30-00", :email=>"marthaelena@senado.gob.mx", :image=>"imgsen/martha_elena_garcia_gomez.jpg", :extention=>"3388-5073" },
{:name=>"Silvia Guadalupe Garza Galván", :state=>"COAHUILA", :phone=>"53-45-30-00", :email=>"silvia.garza@senado.gob.mx", :image=>"imgsen/silvia_guadalupe_garza_galvan.jpg", :extention=>"3337-3446" },
{:name=>"Mariana Gómez del Campo Gurza", :state=>"", :phone=>"53-45-30-00", :email=>"mariana@senado.gob.mx", :image=>"imgsen/mariana_gomez_del_campo.jpg", :extention=>"3019-3020" },
{:name=>"Sonia Mendoza Díaz", :state=>"SAN LUIS POTOSI", :phone=>"53-45-30-00", :email=>"sonia.mendoza@senado.gob.mx", :image=>"imgsen/sonia_mendoza_diaz.jpg", :extention=>"3403" },
{:name=>"Ma. del Pilar Ortega Martínez", :state=>"", :phone=>"53-45-30-00", :email=>"pilar.ortega@pan.@senado.gob.mx", :image=>"imgsen/Ortega_Martinez.jpg", :extention=>"3024-5174" },
{:name=>"Maki Esther Ortiz Domínguez", :state=>"TAMAULIPAS", :phone=>"53-45-30-00", :email=>"maki.ortiz@senado.gob.mx", :image=>"imgsen/maki_esther_ortiz_dominguez.jpg", :extention=>"5440-3393" },
{:name=>"Laura Angélica Rojas Hernández", :state=>"", :phone=>"53-45-30-00", :email=>"laura.rojas@senado.gob.mx", :image=>"imgsen/laura_angelica_rojas_hernandez.jpg", :extention=>"5250-3808-3092" },
{:name=>"María Marcela Torres Peimbert", :state=>"QUERETARO", :phone=>"53-45-30-00", :email=>"marcela.torres@senado.gob.mx", :image=>"imgsen/maria_marcela_torres_peimbert.jpg", :extention=>"5201-3261" },
{:name=>"María Alejandra Barrales Magdaleno", :state=>"DISTRITO FEDERAL", :phone=>"53-45-30-00", :email=>"alejandra.barrales@senado.gob.mx", :image=>"imgsen/maria_alejandra_barrales_magdaleno.jpg", :extention=>"5390" },
{:name=>"Luz María Beristain Navarrete", :state=>"QUINTANA ROO", :phone=>"53-45-30-00", :email=>"luz.beristain@senado.gob.mx", :image=>"imgsen/luz_maria_beristain_navarrete.jpg", :extention=>"3144-5396" },
{:name=>"Lorena Cuéllar Cisneros", :state=>"TLAXCALA", :phone=>"53-45-30-00", :email=>"lorena.cuellar@senado.gob.mx", :image=>"imgsen/lorena_cuellar_cisneros.jpg", :extention=>"3198" },
{:name=>"Angélica De la Peña Gómez", :state=>"", :phone=>"53-45-30-00", :email=>"angelicadelapena@senado.gob.mx", :image=>"imgsen/angelica_de_la_pena_gomez.jpg", :extention=>"3127-3519" },
{:name=>"Iris Vianey Mendoza Mendoza", :state=>"", :phone=>"53-45-30-00", :email=>"imendozam@senado.gob.mx", :image=>"imgsen/iris_vianey_mendoza.jpg", :extention=>"" },
{:name=>"Dolores Padierna Luna", :state=>"", :phone=>"53-45-30-00", :email=>"dolorespadiernaluna@senado.gob.mx", :image=>"imgsen/dolores_padierna_luna.jpg", :extention=>"3545-5196" },
{:name=>"María Elena Barrera Tapia", :state=>"MEXICO", :phone=>"53-45-30-00", :email=>"mariaelena@senado.gob.mx", :image=>"imgsen/maria_elena_barrera_tapia.jpg", :extention=>"5398-5439" },
{:name=>"Ninfa Salinas Sada", :state=>"", :phone=>"53-45-30-00", :email=>"ninfa.salinas@senado.gob.mx", :image=>"imgsen/ninfa_clara_salinas_sada.jpg", :extention=>"" },
{:name=>"Ana Gabriela Guevara Espinoza", :state=>"", :phone=>"53-45-30-00", :email=>"gguevara@senado.gob.mx", :image=>"imgsen/ana_gabriela_guevara_espinosa.jpg", :extention=>"5339" },
{:name=>"Martha Palafox Gutiérrez", :state=>"TLAXCALA", :phone=>"53-45-30-00", :email=>"martha.palafox@senado.gob.mx", :image=>"imgsen/martha_palafox_gutierrez.jpg", :extention=>"3113" },
{:name=>"Mónica Tzasna Arriola Gordillo", :state=>"", :phone=>"53-45-30-00", :email=>"monica.arriola@senado.gob.mx", :image=>"imgsen/monica_tzasna_arriola_gordillo.jpg", :extention=>"3302-3237" },
{:name=>"Layda Sansores San Román", :state=>"", :phone=>"53-45-30-00", :email=>"layda.sansores@senado.gob.mx", :image=>"imgsen/layda_elena_sansores_san_roman.jpg", :extention=>"3254-5160-5165" },
]

senators.each do |attributes|
  Senator.create do |s|
    s.name = attributes[:name]
    s.state = attributes[:state]
    s.phone = attributes[:phone]
    s.email = attributes[:email]
    s.image = attributes[:image]
    s.extention = attributes[:extention]
  end
end

puts "termine senadores"
